# Generated by Django 2.2 on 2020-11-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='home_images')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/%y/%m/%d')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Earth.AllCategories')),
            ],
        ),
    ]
